/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.bookings;

import com.squareup.square.bookings.types.BulkDeleteBookingCustomAttributesRequest;
import com.squareup.square.bookings.types.BulkUpsertBookingCustomAttributesRequest;
import com.squareup.square.bookings.types.DeleteCustomAttributesRequest;
import com.squareup.square.bookings.types.GetCustomAttributesRequest;
import com.squareup.square.bookings.types.ListCustomAttributesRequest;
import com.squareup.square.bookings.types.UpsertBookingCustomAttributeRequest;
import com.squareup.square.core.ClientOptions;
import com.squareup.square.core.RequestOptions;
import com.squareup.square.core.SyncPagingIterable;
import com.squareup.square.types.BulkDeleteBookingCustomAttributesResponse;
import com.squareup.square.types.BulkUpsertBookingCustomAttributesResponse;
import com.squareup.square.types.CustomAttribute;
import com.squareup.square.types.DeleteBookingCustomAttributeResponse;
import com.squareup.square.types.RetrieveBookingCustomAttributeResponse;
import com.squareup.square.types.UpsertBookingCustomAttributeResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncCustomAttributesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawCustomAttributesClient rawClient;

    public AsyncCustomAttributesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawCustomAttributesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawCustomAttributesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Bulk deletes bookings custom attributes.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<BulkDeleteBookingCustomAttributesResponse> batchDelete(
            BulkDeleteBookingCustomAttributesRequest request) {
        return this.rawClient.batchDelete(request).thenApply(response -> response.body());
    }

    /**
     * Bulk deletes bookings custom attributes.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<BulkDeleteBookingCustomAttributesResponse> batchDelete(
            BulkDeleteBookingCustomAttributesRequest request, RequestOptions requestOptions) {
        return this.rawClient.batchDelete(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Bulk upserts bookings custom attributes.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<BulkUpsertBookingCustomAttributesResponse> batchUpsert(
            BulkUpsertBookingCustomAttributesRequest request) {
        return this.rawClient.batchUpsert(request).thenApply(response -> response.body());
    }

    /**
     * Bulk upserts bookings custom attributes.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<BulkUpsertBookingCustomAttributesResponse> batchUpsert(
            BulkUpsertBookingCustomAttributesRequest request, RequestOptions requestOptions) {
        return this.rawClient.batchUpsert(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists a booking's custom attributes.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_READ</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_READ</code> and <code>APPOINTMENTS_READ</code> for the OAuth scope.</p>
     */
    public CompletableFuture<SyncPagingIterable<CustomAttribute>> list(ListCustomAttributesRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Lists a booking's custom attributes.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_READ</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_READ</code> and <code>APPOINTMENTS_READ</code> for the OAuth scope.</p>
     */
    public CompletableFuture<SyncPagingIterable<CustomAttribute>> list(
            ListCustomAttributesRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieves a bookings custom attribute.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_READ</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_READ</code> and <code>APPOINTMENTS_READ</code> for the OAuth scope.</p>
     */
    public CompletableFuture<RetrieveBookingCustomAttributeResponse> get(GetCustomAttributesRequest request) {
        return this.rawClient.get(request).thenApply(response -> response.body());
    }

    /**
     * Retrieves a bookings custom attribute.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_READ</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_READ</code> and <code>APPOINTMENTS_READ</code> for the OAuth scope.</p>
     */
    public CompletableFuture<RetrieveBookingCustomAttributeResponse> get(
            GetCustomAttributesRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Upserts a bookings custom attribute.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<UpsertBookingCustomAttributeResponse> upsert(UpsertBookingCustomAttributeRequest request) {
        return this.rawClient.upsert(request).thenApply(response -> response.body());
    }

    /**
     * Upserts a bookings custom attribute.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<UpsertBookingCustomAttributeResponse> upsert(
            UpsertBookingCustomAttributeRequest request, RequestOptions requestOptions) {
        return this.rawClient.upsert(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Deletes a bookings custom attribute.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<DeleteBookingCustomAttributeResponse> delete(DeleteCustomAttributesRequest request) {
        return this.rawClient.delete(request).thenApply(response -> response.body());
    }

    /**
     * Deletes a bookings custom attribute.
     * <p>To call this endpoint with buyer-level permissions, set <code>APPOINTMENTS_WRITE</code> for the OAuth scope.
     * To call this endpoint with seller-level permissions, set <code>APPOINTMENTS_ALL_WRITE</code> and <code>APPOINTMENTS_WRITE</code> for the OAuth scope.</p>
     * <p>For calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to <em>Appointments Plus</em>
     * or <em>Appointments Premium</em>.</p>
     */
    public CompletableFuture<DeleteBookingCustomAttributeResponse> delete(
            DeleteCustomAttributesRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
    }
}
