/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.merchants.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.Nullable;
import com.squareup.square.core.NullableNonemptyFilter;
import com.squareup.square.core.ObjectMappers;
import com.squareup.square.types.CustomAttribute;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpsertMerchantCustomAttributeRequest.Builder.class)
public final class UpsertMerchantCustomAttributeRequest {
    private final String merchantId;

    private final String key;

    private final CustomAttribute customAttribute;

    private final Optional<String> idempotencyKey;

    private final Map<String, Object> additionalProperties;

    private UpsertMerchantCustomAttributeRequest(
            String merchantId,
            String key,
            CustomAttribute customAttribute,
            Optional<String> idempotencyKey,
            Map<String, Object> additionalProperties) {
        this.merchantId = merchantId;
        this.key = key;
        this.customAttribute = customAttribute;
        this.idempotencyKey = idempotencyKey;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The ID of the target <a href="entity:Merchant">merchant</a>.
     */
    @JsonProperty("merchant_id")
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * @return The key of the custom attribute to create or update. This key must match the <code>key</code> of a
     * custom attribute definition in the Square seller account. If the requesting application is not
     * the definition owner, you must use the qualified key.
     */
    @JsonProperty("key")
    public String getKey() {
        return key;
    }

    /**
     * @return The custom attribute to create or update, with the following fields:
     * <ul>
     * <li><code>value</code>. This value must conform to the <code>schema</code> specified by the definition.
     * For more information, see <a href="https://developer.squareup.com/docs/devtools/customattributes/overview#supported-data-types">Supported data types</a>.</li>
     * <li>The version field must match the current version of the custom attribute definition to enable
     * <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency">optimistic concurrency</a>
     * If this is not important for your application, version can be set to -1. For any other values, the request fails with a BAD_REQUEST error.</li>
     * </ul>
     */
    @JsonProperty("custom_attribute")
    public CustomAttribute getCustomAttribute() {
        return customAttribute;
    }

    /**
     * @return A unique identifier for this request, used to ensure idempotency. For more information,
     * see <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency">Idempotency</a>.
     */
    @JsonIgnore
    public Optional<String> getIdempotencyKey() {
        if (idempotencyKey == null) {
            return Optional.empty();
        }
        return idempotencyKey;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("idempotency_key")
    private Optional<String> _getIdempotencyKey() {
        return idempotencyKey;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpsertMerchantCustomAttributeRequest
                && equalTo((UpsertMerchantCustomAttributeRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpsertMerchantCustomAttributeRequest other) {
        return merchantId.equals(other.merchantId)
                && key.equals(other.key)
                && customAttribute.equals(other.customAttribute)
                && idempotencyKey.equals(other.idempotencyKey);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.merchantId, this.key, this.customAttribute, this.idempotencyKey);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MerchantIdStage builder() {
        return new Builder();
    }

    public interface MerchantIdStage {
        /**
         * <p>The ID of the target <a href="entity:Merchant">merchant</a>.</p>
         */
        KeyStage merchantId(@NotNull String merchantId);

        Builder from(UpsertMerchantCustomAttributeRequest other);
    }

    public interface KeyStage {
        /**
         * <p>The key of the custom attribute to create or update. This key must match the <code>key</code> of a
         * custom attribute definition in the Square seller account. If the requesting application is not
         * the definition owner, you must use the qualified key.</p>
         */
        CustomAttributeStage key(@NotNull String key);
    }

    public interface CustomAttributeStage {
        /**
         * <p>The custom attribute to create or update, with the following fields:</p>
         * <ul>
         * <li><code>value</code>. This value must conform to the <code>schema</code> specified by the definition.
         * For more information, see <a href="https://developer.squareup.com/docs/devtools/customattributes/overview#supported-data-types">Supported data types</a>.</li>
         * <li>The version field must match the current version of the custom attribute definition to enable
         * <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency">optimistic concurrency</a>
         * If this is not important for your application, version can be set to -1. For any other values, the request fails with a BAD_REQUEST error.</li>
         * </ul>
         */
        _FinalStage customAttribute(@NotNull CustomAttribute customAttribute);
    }

    public interface _FinalStage {
        UpsertMerchantCustomAttributeRequest build();

        /**
         * <p>A unique identifier for this request, used to ensure idempotency. For more information,
         * see <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency">Idempotency</a>.</p>
         */
        _FinalStage idempotencyKey(Optional<String> idempotencyKey);

        _FinalStage idempotencyKey(String idempotencyKey);

        _FinalStage idempotencyKey(Nullable<String> idempotencyKey);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MerchantIdStage, KeyStage, CustomAttributeStage, _FinalStage {
        private String merchantId;

        private String key;

        private CustomAttribute customAttribute;

        private Optional<String> idempotencyKey = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpsertMerchantCustomAttributeRequest other) {
            merchantId(other.getMerchantId());
            key(other.getKey());
            customAttribute(other.getCustomAttribute());
            idempotencyKey(other.getIdempotencyKey());
            return this;
        }

        /**
         * <p>The ID of the target <a href="entity:Merchant">merchant</a>.</p>
         * <p>The ID of the target <a href="entity:Merchant">merchant</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("merchant_id")
        public KeyStage merchantId(@NotNull String merchantId) {
            this.merchantId = Objects.requireNonNull(merchantId, "merchantId must not be null");
            return this;
        }

        /**
         * <p>The key of the custom attribute to create or update. This key must match the <code>key</code> of a
         * custom attribute definition in the Square seller account. If the requesting application is not
         * the definition owner, you must use the qualified key.</p>
         * <p>The key of the custom attribute to create or update. This key must match the <code>key</code> of a
         * custom attribute definition in the Square seller account. If the requesting application is not
         * the definition owner, you must use the qualified key.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("key")
        public CustomAttributeStage key(@NotNull String key) {
            this.key = Objects.requireNonNull(key, "key must not be null");
            return this;
        }

        /**
         * <p>The custom attribute to create or update, with the following fields:</p>
         * <ul>
         * <li><code>value</code>. This value must conform to the <code>schema</code> specified by the definition.
         * For more information, see <a href="https://developer.squareup.com/docs/devtools/customattributes/overview#supported-data-types">Supported data types</a>.</li>
         * <li>The version field must match the current version of the custom attribute definition to enable
         * <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency">optimistic concurrency</a>
         * If this is not important for your application, version can be set to -1. For any other values, the request fails with a BAD_REQUEST error.</li>
         * </ul>
         * <p>The custom attribute to create or update, with the following fields:</p>
         * <ul>
         * <li><code>value</code>. This value must conform to the <code>schema</code> specified by the definition.
         * For more information, see <a href="https://developer.squareup.com/docs/devtools/customattributes/overview#supported-data-types">Supported data types</a>.</li>
         * <li>The version field must match the current version of the custom attribute definition to enable
         * <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/optimistic-concurrency">optimistic concurrency</a>
         * If this is not important for your application, version can be set to -1. For any other values, the request fails with a BAD_REQUEST error.</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("custom_attribute")
        public _FinalStage customAttribute(@NotNull CustomAttribute customAttribute) {
            this.customAttribute = Objects.requireNonNull(customAttribute, "customAttribute must not be null");
            return this;
        }

        /**
         * <p>A unique identifier for this request, used to ensure idempotency. For more information,
         * see <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency">Idempotency</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idempotencyKey(Nullable<String> idempotencyKey) {
            if (idempotencyKey.isNull()) {
                this.idempotencyKey = null;
            } else if (idempotencyKey.isEmpty()) {
                this.idempotencyKey = Optional.empty();
            } else {
                this.idempotencyKey = Optional.of(idempotencyKey.get());
            }
            return this;
        }

        /**
         * <p>A unique identifier for this request, used to ensure idempotency. For more information,
         * see <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency">Idempotency</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idempotencyKey(String idempotencyKey) {
            this.idempotencyKey = Optional.ofNullable(idempotencyKey);
            return this;
        }

        /**
         * <p>A unique identifier for this request, used to ensure idempotency. For more information,
         * see <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency">Idempotency</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "idempotency_key", nulls = Nulls.SKIP)
        public _FinalStage idempotencyKey(Optional<String> idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        @java.lang.Override
        public UpsertMerchantCustomAttributeRequest build() {
            return new UpsertMerchantCustomAttributeRequest(
                    merchantId, key, customAttribute, idempotencyKey, additionalProperties);
        }
    }
}
