package com.squareup.square.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonGetter;


/**
 * This is a model class for Card type.
 */
public class Card {

    /**
     * Initialization constructor.
     * @param id
     * @param cardBrand
     * @param last4
     * @param expMonth
     * @param expYear
     * @param cardholderName
     * @param billingAddress
     * @param fingerprint
     * @param cardType
     * @param prepaidType
     * @param bin
     */
    @JsonCreator
    public Card(
            @JsonProperty("id") String id,
            @JsonProperty("card_brand") String cardBrand,
            @JsonProperty("last_4") String last4,
            @JsonProperty("exp_month") Long expMonth,
            @JsonProperty("exp_year") Long expYear,
            @JsonProperty("cardholder_name") String cardholderName,
            @JsonProperty("billing_address") Address billingAddress,
            @JsonProperty("fingerprint") String fingerprint,
            @JsonProperty("card_type") String cardType,
            @JsonProperty("prepaid_type") String prepaidType,
            @JsonProperty("bin") String bin) {
        this.id = id;
        this.cardBrand = cardBrand;
        this.last4 = last4;
        this.expMonth = expMonth;
        this.expYear = expYear;
        this.cardholderName = cardholderName;
        this.billingAddress = billingAddress;
        this.fingerprint = fingerprint;
        this.cardType = cardType;
        this.prepaidType = prepaidType;
        this.bin = bin;
    }

    private final String id;
    private final String cardBrand;
    private final String last4;
    private final Long expMonth;
    private final Long expYear;
    private final String cardholderName;
    private final Address billingAddress;
    private final String fingerprint;
    private final String cardType;
    private final String prepaidType;
    private final String bin;
    /**
     * Getter for Id.
     * Unique ID for this card. Generated by Square.
     */
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    /**
     * Getter for CardBrand.
     * Indicates a card's brand, such as `VISA` or `MASTERCARD`.
     */
    @JsonGetter("card_brand")
    public String getCardBrand() {
        return this.cardBrand;
    }

    /**
     * Getter for Last4.
     * The last 4 digits of the card number.
     */
    @JsonGetter("last_4")
    public String getLast4() {
        return this.last4;
    }

    /**
     * Getter for ExpMonth.
     * The expiration month of the associated card as an integer between 1 and 12.
     */
    @JsonGetter("exp_month")
    public Long getExpMonth() {
        return this.expMonth;
    }

    /**
     * Getter for ExpYear.
     * The four-digit year of the card's expiration date.
     */
    @JsonGetter("exp_year")
    public Long getExpYear() {
        return this.expYear;
    }

    /**
     * Getter for CardholderName.
     * The name of the cardholder.
     */
    @JsonGetter("cardholder_name")
    public String getCardholderName() {
        return this.cardholderName;
    }

    /**
     * Getter for BillingAddress.
     * Represents a physical address.
     */
    @JsonGetter("billing_address")
    public Address getBillingAddress() {
        return this.billingAddress;
    }

    /**
     * Getter for Fingerprint.
     * __Not currently set.__ Intended as a Square-assigned identifier, based
     * on the card number, to identify the card across multiple locations within a
     * single application.
     */
    @JsonGetter("fingerprint")
    public String getFingerprint() {
        return this.fingerprint;
    }

    /**
     * Getter for CardType.
     * Indicates a card's type, such as `CREDIT` or `DEBIT`.
     */
    @JsonGetter("card_type")
    public String getCardType() {
        return this.cardType;
    }

    /**
     * Getter for PrepaidType.
     * Indicates a card's prepaid type, such as `NOT_PREPAID` or `PREPAID`.
     */
    @JsonGetter("prepaid_type")
    public String getPrepaidType() {
        return this.prepaidType;
    }

    /**
     * Getter for Bin.
     * The first six digits of the card number, known as the Bank Identification Number (BIN). Only the Payments API
     * returns this field.
     */
    @JsonGetter("bin")
    public String getBin() {
        return this.bin;
    }

 
    @Override
    public int hashCode() {
        return Objects.hash(id, cardBrand, last4, expMonth, expYear, cardholderName, billingAddress,
            fingerprint, cardType, prepaidType, bin);
    }

    @Override
    public boolean equals(Object obj) {
        if(obj == this) {
            return true;
        }
        if(!(obj instanceof Card)) {
            return false;
        }
        Card card = (Card) obj;
        return Objects.equals(id, card.id) &&
            Objects.equals(cardBrand, card.cardBrand) &&
            Objects.equals(last4, card.last4) &&
            Objects.equals(expMonth, card.expMonth) &&
            Objects.equals(expYear, card.expYear) &&
            Objects.equals(cardholderName, card.cardholderName) &&
            Objects.equals(billingAddress, card.billingAddress) &&
            Objects.equals(fingerprint, card.fingerprint) &&
            Objects.equals(cardType, card.cardType) &&
            Objects.equals(prepaidType, card.prepaidType) &&
            Objects.equals(bin, card.bin);
    }

    /**
     * Builds a new {@link Card.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Card.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
            .id(getId())
            .cardBrand(getCardBrand())
            .last4(getLast4())
            .expMonth(getExpMonth())
            .expYear(getExpYear())
            .cardholderName(getCardholderName())
            .billingAddress(getBillingAddress())
            .fingerprint(getFingerprint())
            .cardType(getCardType())
            .prepaidType(getPrepaidType())
            .bin(getBin());
            return builder;
    }

    /**
     * Class to build instances of {@link Card}
     */
    public static class Builder {
        private String id;
        private String cardBrand;
        private String last4;
        private Long expMonth;
        private Long expYear;
        private String cardholderName;
        private Address billingAddress;
        private String fingerprint;
        private String cardType;
        private String prepaidType;
        private String bin;

        /**
         * Initialization constructor
         */
        public Builder() {
           
        }

        /**
         * Setter for id
         * @param id
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }
        /**
         * Setter for cardBrand
         * @param cardBrand
         * @return Builder
         */
        public Builder cardBrand(String cardBrand) {
            this.cardBrand = cardBrand;
            return this;
        }
        /**
         * Setter for last4
         * @param last4
         * @return Builder
         */
        public Builder last4(String last4) {
            this.last4 = last4;
            return this;
        }
        /**
         * Setter for expMonth
         * @param expMonth
         * @return Builder
         */
        public Builder expMonth(Long expMonth) {
            this.expMonth = expMonth;
            return this;
        }
        /**
         * Setter for expYear
         * @param expYear
         * @return Builder
         */
        public Builder expYear(Long expYear) {
            this.expYear = expYear;
            return this;
        }
        /**
         * Setter for cardholderName
         * @param cardholderName
         * @return Builder
         */
        public Builder cardholderName(String cardholderName) {
            this.cardholderName = cardholderName;
            return this;
        }
        /**
         * Setter for billingAddress
         * @param billingAddress
         * @return Builder
         */
        public Builder billingAddress(Address billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }
        /**
         * Setter for fingerprint
         * @param fingerprint
         * @return Builder
         */
        public Builder fingerprint(String fingerprint) {
            this.fingerprint = fingerprint;
            return this;
        }
        /**
         * Setter for cardType
         * @param cardType
         * @return Builder
         */
        public Builder cardType(String cardType) {
            this.cardType = cardType;
            return this;
        }
        /**
         * Setter for prepaidType
         * @param prepaidType
         * @return Builder
         */
        public Builder prepaidType(String prepaidType) {
            this.prepaidType = prepaidType;
            return this;
        }
        /**
         * Setter for bin
         * @param bin
         * @return Builder
         */
        public Builder bin(String bin) {
            this.bin = bin;
            return this;
        }

        /**
         * Builds a new {@link Card} object using the set fields.
         * @return {@link Card}
         */
        public Card build() {
            return new Card(id,
                cardBrand,
                last4,
                expMonth,
                expYear,
                cardholderName,
                billingAddress,
                fingerprint,
                cardType,
                prepaidType,
                bin);
        }
    }
}
