package com.squareup.square.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonGetter;

public class CreateCustomerCardRequest {

    @JsonCreator
    public CreateCustomerCardRequest(
            @JsonProperty("card_nonce") String cardNonce,
            @JsonProperty("billing_address") Address billingAddress,
            @JsonProperty("cardholder_name") String cardholderName,
            @JsonProperty("verification_token") String verificationToken) {
        this.cardNonce = cardNonce;
        this.billingAddress = billingAddress;
        this.cardholderName = cardholderName;
        this.verificationToken = verificationToken;
    }

    private final String cardNonce;
    private final Address billingAddress;
    private final String cardholderName;
    private final String verificationToken;

    @Override
    public int hashCode() {
        return Objects.hash(cardNonce, billingAddress, cardholderName, verificationToken);
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof CreateCustomerCardRequest)) {
            return false;
        }
        CreateCustomerCardRequest createCustomerCardRequest = (CreateCustomerCardRequest) o;
        return Objects.equals(cardNonce, createCustomerCardRequest.cardNonce) &&
            Objects.equals(billingAddress, createCustomerCardRequest.billingAddress) &&
            Objects.equals(cardholderName, createCustomerCardRequest.cardholderName) &&
            Objects.equals(verificationToken, createCustomerCardRequest.verificationToken);
    }

    /**
     * Getter for CardNonce.
     * A card nonce representing the credit card to link to the customer.
     * Card nonces are generated by the Square Payment Form when customers enter
     * their card information. See
     * [Embedding the payment form](https://developer.squareup.com/docs/payment-form/payment-form-walkthrough) for
     * more information.
     * __NOTE:__ Card nonces generated by digital wallets (e.g., Apple Pay)
     * cannot be used to create a customer card.
     */
    @JsonGetter("card_nonce")
    public String getCardNonce() { 
        return this.cardNonce;
    }

    /**
     * Getter for BillingAddress.
     * Represents a physical address.
     */
    @JsonGetter("billing_address")
    public Address getBillingAddress() { 
        return this.billingAddress;
    }

    /**
     * Getter for CardholderName.
     * The full name printed on the credit card.
     */
    @JsonGetter("cardholder_name")
    public String getCardholderName() { 
        return this.cardholderName;
    }

    /**
     * Getter for VerificationToken.
     * An identifying token generated by `SqPaymentForm.verifyBuyer()`.
     * Verification tokens encapsulate customer device information and 3-D Secure
     * challenge results to indicate that Square has verified the buyer identity.
     */
    @JsonGetter("verification_token")
    public String getVerificationToken() { 
        return this.verificationToken;
    }

 
    public Builder toBuilder() {
        Builder builder = new Builder(cardNonce)
            .billingAddress(getBillingAddress())
            .cardholderName(getCardholderName())
            .verificationToken(getVerificationToken());
            return builder;
    }

    public static class Builder {
        private String cardNonce;
        private Address billingAddress;
        private String cardholderName;
        private String verificationToken;

        public Builder(String cardNonce) {
            this.cardNonce = cardNonce;
        }

        public Builder cardNonce(String value) {
            cardNonce = value;
            return this;
        }
        public Builder billingAddress(Address value) {
            billingAddress = value;
            return this;
        }
        public Builder cardholderName(String value) {
            cardholderName = value;
            return this;
        }
        public Builder verificationToken(String value) {
            verificationToken = value;
            return this;
        }

        public CreateCustomerCardRequest build() {
            return new CreateCustomerCardRequest(cardNonce,
                billingAddress,
                cardholderName,
                verificationToken);
        }
    }
}
