package com.squareup.square.models;

import java.util.List;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonGetter;


/**
 * This is a model class for TerminalCheckout type.
 */
public class TerminalCheckout {

    /**
     * Initialization constructor.
     * @param amountMoney
     * @param deviceOptions
     * @param id
     * @param referenceId
     * @param note
     * @param deadlineDuration
     * @param status
     * @param cancelReason
     * @param paymentIds
     * @param createdAt
     * @param updatedAt
     */
    @JsonCreator
    public TerminalCheckout(
            @JsonProperty("amount_money") Money amountMoney,
            @JsonProperty("device_options") DeviceCheckoutOptions deviceOptions,
            @JsonProperty("id") String id,
            @JsonProperty("reference_id") String referenceId,
            @JsonProperty("note") String note,
            @JsonProperty("deadline_duration") String deadlineDuration,
            @JsonProperty("status") String status,
            @JsonProperty("cancel_reason") String cancelReason,
            @JsonProperty("payment_ids") List<String> paymentIds,
            @JsonProperty("created_at") String createdAt,
            @JsonProperty("updated_at") String updatedAt) {
        this.id = id;
        this.amountMoney = amountMoney;
        this.referenceId = referenceId;
        this.note = note;
        this.deviceOptions = deviceOptions;
        this.deadlineDuration = deadlineDuration;
        this.status = status;
        this.cancelReason = cancelReason;
        this.paymentIds = paymentIds;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    private final String id;
    private final Money amountMoney;
    private final String referenceId;
    private final String note;
    private final DeviceCheckoutOptions deviceOptions;
    private final String deadlineDuration;
    private final String status;
    private final String cancelReason;
    private final List<String> paymentIds;
    private final String createdAt;
    private final String updatedAt;
    /**
     * Getter for Id.
     * A unique ID for this `TerminalCheckout`
     */
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    /**
     * Getter for AmountMoney.
     * Represents an amount of money. `Money` fields can be signed or unsigned.
     * Fields that do not explicitly define whether they are signed or unsigned are
     * considered unsigned and can only hold positive amounts. For signed fields, the
     * sign of the value indicates the purpose of the money transfer. See
     * [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
     * for more information.
     */
    @JsonGetter("amount_money")
    public Money getAmountMoney() {
        return this.amountMoney;
    }

    /**
     * Getter for ReferenceId.
     * An optional user-defined reference ID which can be used to associate
     * this TerminalCheckout to another entity in an external system. For example, an order
     * ID generated by a third-party shopping cart. Will also be associated with any payments
     * used to complete the checkout.
     */
    @JsonGetter("reference_id")
    public String getReferenceId() {
        return this.referenceId;
    }

    /**
     * Getter for Note.
     * An optional note to associate with the checkout, as well any payments used to complete the checkout.
     */
    @JsonGetter("note")
    public String getNote() {
        return this.note;
    }

    /**
     * Getter for DeviceOptions.
     */
    @JsonGetter("device_options")
    public DeviceCheckoutOptions getDeviceOptions() {
        return this.deviceOptions;
    }

    /**
     * Getter for DeadlineDuration.
     * The duration as an RFC 3339 duration, after which the checkout will be automatically canceled.
     * TerminalCheckouts that are PENDING will be automatically CANCELED and have a cancellation reason
     * of “TIMED\_OUT”.
     * Default: 5 minutes from creation
     * Maximum: 5 minutes
     */
    @JsonGetter("deadline_duration")
    public String getDeadlineDuration() {
        return this.deadlineDuration;
    }

    /**
     * Getter for Status.
     * The status of the `TerminalCheckout`.
     * Options: PENDING, IN\_PROGRESS, CANCELED, COMPLETED
     */
    @JsonGetter("status")
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for CancelReason.
     */
    @JsonGetter("cancel_reason")
    public String getCancelReason() {
        return this.cancelReason;
    }

    /**
     * Getter for PaymentIds.
     * A list of payments created by this `TerminalCheckout`.
     */
    @JsonGetter("payment_ids")
    public List<String> getPaymentIds() {
        return this.paymentIds;
    }

    /**
     * Getter for CreatedAt.
     * The time when the `TerminalCheckout` was created as an RFC 3339 timestamp.
     */
    @JsonGetter("created_at")
    public String getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for UpdatedAt.
     * The time when the `TerminalCheckout` was last updated as an RFC 3339 timestamp.
     */
    @JsonGetter("updated_at")
    public String getUpdatedAt() {
        return this.updatedAt;
    }

 
    @Override
    public int hashCode() {
        return Objects.hash(id, amountMoney, referenceId, note, deviceOptions, deadlineDuration,
            status, cancelReason, paymentIds, createdAt, updatedAt);
    }

    @Override
    public boolean equals(Object obj) {
        if(obj == this) {
            return true;
        }
        if(!(obj instanceof TerminalCheckout)) {
            return false;
        }
        TerminalCheckout terminalCheckout = (TerminalCheckout) obj;
        return Objects.equals(id, terminalCheckout.id) &&
            Objects.equals(amountMoney, terminalCheckout.amountMoney) &&
            Objects.equals(referenceId, terminalCheckout.referenceId) &&
            Objects.equals(note, terminalCheckout.note) &&
            Objects.equals(deviceOptions, terminalCheckout.deviceOptions) &&
            Objects.equals(deadlineDuration, terminalCheckout.deadlineDuration) &&
            Objects.equals(status, terminalCheckout.status) &&
            Objects.equals(cancelReason, terminalCheckout.cancelReason) &&
            Objects.equals(paymentIds, terminalCheckout.paymentIds) &&
            Objects.equals(createdAt, terminalCheckout.createdAt) &&
            Objects.equals(updatedAt, terminalCheckout.updatedAt);
    }

    /**
     * Builds a new {@link TerminalCheckout.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TerminalCheckout.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(amountMoney,
            deviceOptions)
            .id(getId())
            .referenceId(getReferenceId())
            .note(getNote())
            .deadlineDuration(getDeadlineDuration())
            .status(getStatus())
            .cancelReason(getCancelReason())
            .paymentIds(getPaymentIds())
            .createdAt(getCreatedAt())
            .updatedAt(getUpdatedAt());
            return builder;
    }

    /**
     * Class to build instances of {@link TerminalCheckout}
     */
    public static class Builder {
        private Money amountMoney;
        private DeviceCheckoutOptions deviceOptions;
        private String id;
        private String referenceId;
        private String note;
        private String deadlineDuration;
        private String status;
        private String cancelReason;
        private List<String> paymentIds;
        private String createdAt;
        private String updatedAt;

        /**
         * Initialization constructor
         */
        public Builder(Money amountMoney,
                DeviceCheckoutOptions deviceOptions) {
            this.amountMoney = amountMoney;
            this.deviceOptions = deviceOptions;
        }

        /**
         * Setter for amountMoney
         * @param amountMoney
         * @return Builder
         */
        public Builder amountMoney(Money amountMoney) {
            this.amountMoney = amountMoney;
            return this;
        }
        /**
         * Setter for deviceOptions
         * @param deviceOptions
         * @return Builder
         */
        public Builder deviceOptions(DeviceCheckoutOptions deviceOptions) {
            this.deviceOptions = deviceOptions;
            return this;
        }
        /**
         * Setter for id
         * @param id
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }
        /**
         * Setter for referenceId
         * @param referenceId
         * @return Builder
         */
        public Builder referenceId(String referenceId) {
            this.referenceId = referenceId;
            return this;
        }
        /**
         * Setter for note
         * @param note
         * @return Builder
         */
        public Builder note(String note) {
            this.note = note;
            return this;
        }
        /**
         * Setter for deadlineDuration
         * @param deadlineDuration
         * @return Builder
         */
        public Builder deadlineDuration(String deadlineDuration) {
            this.deadlineDuration = deadlineDuration;
            return this;
        }
        /**
         * Setter for status
         * @param status
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }
        /**
         * Setter for cancelReason
         * @param cancelReason
         * @return Builder
         */
        public Builder cancelReason(String cancelReason) {
            this.cancelReason = cancelReason;
            return this;
        }
        /**
         * Setter for paymentIds
         * @param paymentIds
         * @return Builder
         */
        public Builder paymentIds(List<String> paymentIds) {
            this.paymentIds = paymentIds;
            return this;
        }
        /**
         * Setter for createdAt
         * @param createdAt
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }
        /**
         * Setter for updatedAt
         * @param updatedAt
         * @return Builder
         */
        public Builder updatedAt(String updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Builds a new {@link TerminalCheckout} object using the set fields.
         * @return {@link TerminalCheckout}
         */
        public TerminalCheckout build() {
            return new TerminalCheckout(amountMoney,
                deviceOptions,
                id,
                referenceId,
                note,
                deadlineDuration,
                status,
                cancelReason,
                paymentIds,
                createdAt,
                updatedAt);
        }
    }
}
