/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.terminal.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import com.squareup.square.types.TerminalCheckoutQuery;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SearchTerminalCheckoutsRequest.Builder.class)
public final class SearchTerminalCheckoutsRequest {
    private final Optional<TerminalCheckoutQuery> query;

    private final Optional<String> cursor;

    private final Optional<Integer> limit;

    private final Map<String, Object> additionalProperties;

    private SearchTerminalCheckoutsRequest(
            Optional<TerminalCheckoutQuery> query,
            Optional<String> cursor,
            Optional<Integer> limit,
            Map<String, Object> additionalProperties) {
        this.query = query;
        this.cursor = cursor;
        this.limit = limit;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Queries Terminal checkouts based on given conditions and the sort order.
     * Leaving these unset returns all checkouts with the default sort order.
     */
    @JsonProperty("query")
    public Optional<TerminalCheckoutQuery> getQuery() {
        return query;
    }

    /**
     * @return A pagination cursor returned by a previous call to this endpoint.
     * Provide this cursor to retrieve the next set of results for the original query.
     * See <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination">Pagination</a> for more information.
     */
    @JsonProperty("cursor")
    public Optional<String> getCursor() {
        return cursor;
    }

    /**
     * @return Limits the number of results returned for a single request.
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SearchTerminalCheckoutsRequest && equalTo((SearchTerminalCheckoutsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SearchTerminalCheckoutsRequest other) {
        return query.equals(other.query) && cursor.equals(other.cursor) && limit.equals(other.limit);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.query, this.cursor, this.limit);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<TerminalCheckoutQuery> query = Optional.empty();

        private Optional<String> cursor = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SearchTerminalCheckoutsRequest other) {
            query(other.getQuery());
            cursor(other.getCursor());
            limit(other.getLimit());
            return this;
        }

        /**
         * <p>Queries Terminal checkouts based on given conditions and the sort order.
         * Leaving these unset returns all checkouts with the default sort order.</p>
         */
        @JsonSetter(value = "query", nulls = Nulls.SKIP)
        public Builder query(Optional<TerminalCheckoutQuery> query) {
            this.query = query;
            return this;
        }

        public Builder query(TerminalCheckoutQuery query) {
            this.query = Optional.ofNullable(query);
            return this;
        }

        /**
         * <p>A pagination cursor returned by a previous call to this endpoint.
         * Provide this cursor to retrieve the next set of results for the original query.
         * See <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination">Pagination</a> for more information.</p>
         */
        @JsonSetter(value = "cursor", nulls = Nulls.SKIP)
        public Builder cursor(Optional<String> cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder cursor(String cursor) {
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        /**
         * <p>Limits the number of results returned for a single request.</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        public SearchTerminalCheckoutsRequest build() {
            return new SearchTerminalCheckoutsRequest(query, cursor, limit, additionalProperties);
        }
    }
}
