/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.Nullable;
import com.squareup.square.core.NullableNonemptyFilter;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BatchGetVendorsRequest.Builder.class)
public final class BatchGetVendorsRequest {
    private final Optional<List<String>> vendorIds;

    private final Map<String, Object> additionalProperties;

    private BatchGetVendorsRequest(Optional<List<String>> vendorIds, Map<String, Object> additionalProperties) {
        this.vendorIds = vendorIds;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return IDs of the <a href="entity:Vendor">Vendor</a> objects to retrieve.
     */
    @JsonIgnore
    public Optional<List<String>> getVendorIds() {
        if (vendorIds == null) {
            return Optional.empty();
        }
        return vendorIds;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("vendor_ids")
    private Optional<List<String>> _getVendorIds() {
        return vendorIds;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BatchGetVendorsRequest && equalTo((BatchGetVendorsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BatchGetVendorsRequest other) {
        return vendorIds.equals(other.vendorIds);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.vendorIds);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> vendorIds = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BatchGetVendorsRequest other) {
            vendorIds(other.getVendorIds());
            return this;
        }

        @JsonSetter(value = "vendor_ids", nulls = Nulls.SKIP)
        public Builder vendorIds(Optional<List<String>> vendorIds) {
            this.vendorIds = vendorIds;
            return this;
        }

        public Builder vendorIds(List<String> vendorIds) {
            this.vendorIds = Optional.ofNullable(vendorIds);
            return this;
        }

        public Builder vendorIds(Nullable<List<String>> vendorIds) {
            if (vendorIds.isNull()) {
                this.vendorIds = null;
            } else if (vendorIds.isEmpty()) {
                this.vendorIds = Optional.empty();
            } else {
                this.vendorIds = Optional.of(vendorIds.get());
            }
            return this;
        }

        public BatchGetVendorsRequest build() {
            return new BatchGetVendorsRequest(vendorIds, additionalProperties);
        }
    }
}
