/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.Nullable;
import com.squareup.square.core.NullableNonemptyFilter;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CatalogQueryItemVariationsForItemOptionValues.Builder.class)
public final class CatalogQueryItemVariationsForItemOptionValues {
    private final Optional<List<String>> itemOptionValueIds;

    private final Map<String, Object> additionalProperties;

    private CatalogQueryItemVariationsForItemOptionValues(
            Optional<List<String>> itemOptionValueIds, Map<String, Object> additionalProperties) {
        this.itemOptionValueIds = itemOptionValueIds;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A set of <code>CatalogItemOptionValue</code> IDs to be used to find associated
     * <code>CatalogItemVariation</code>s. All ItemVariations that contain all of the given
     * Item Option Values (in any order) will be returned.
     */
    @JsonIgnore
    public Optional<List<String>> getItemOptionValueIds() {
        if (itemOptionValueIds == null) {
            return Optional.empty();
        }
        return itemOptionValueIds;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("item_option_value_ids")
    private Optional<List<String>> _getItemOptionValueIds() {
        return itemOptionValueIds;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CatalogQueryItemVariationsForItemOptionValues
                && equalTo((CatalogQueryItemVariationsForItemOptionValues) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CatalogQueryItemVariationsForItemOptionValues other) {
        return itemOptionValueIds.equals(other.itemOptionValueIds);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.itemOptionValueIds);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> itemOptionValueIds = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CatalogQueryItemVariationsForItemOptionValues other) {
            itemOptionValueIds(other.getItemOptionValueIds());
            return this;
        }

        @JsonSetter(value = "item_option_value_ids", nulls = Nulls.SKIP)
        public Builder itemOptionValueIds(Optional<List<String>> itemOptionValueIds) {
            this.itemOptionValueIds = itemOptionValueIds;
            return this;
        }

        public Builder itemOptionValueIds(List<String> itemOptionValueIds) {
            this.itemOptionValueIds = Optional.ofNullable(itemOptionValueIds);
            return this;
        }

        public Builder itemOptionValueIds(Nullable<List<String>> itemOptionValueIds) {
            if (itemOptionValueIds.isNull()) {
                this.itemOptionValueIds = null;
            } else if (itemOptionValueIds.isEmpty()) {
                this.itemOptionValueIds = Optional.empty();
            } else {
                this.itemOptionValueIds = Optional.of(itemOptionValueIds.get());
            }
            return this;
        }

        public CatalogQueryItemVariationsForItemOptionValues build() {
            return new CatalogQueryItemVariationsForItemOptionValues(itemOptionValueIds, additionalProperties);
        }
    }
}
