/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateInvoiceAttachmentResponse.Builder.class)
public final class CreateInvoiceAttachmentResponse {
    private final Optional<InvoiceAttachment> attachment;

    private final Optional<List<Error>> errors;

    private final Map<String, Object> additionalProperties;

    private CreateInvoiceAttachmentResponse(
            Optional<InvoiceAttachment> attachment,
            Optional<List<Error>> errors,
            Map<String, Object> additionalProperties) {
        this.attachment = attachment;
        this.errors = errors;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Metadata about the attachment that was added to the invoice.
     */
    @JsonProperty("attachment")
    public Optional<InvoiceAttachment> getAttachment() {
        return attachment;
    }

    /**
     * @return Information about errors encountered during the request.
     */
    @JsonProperty("errors")
    public Optional<List<Error>> getErrors() {
        return errors;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateInvoiceAttachmentResponse && equalTo((CreateInvoiceAttachmentResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateInvoiceAttachmentResponse other) {
        return attachment.equals(other.attachment) && errors.equals(other.errors);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.attachment, this.errors);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<InvoiceAttachment> attachment = Optional.empty();

        private Optional<List<Error>> errors = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateInvoiceAttachmentResponse other) {
            attachment(other.getAttachment());
            errors(other.getErrors());
            return this;
        }

        @JsonSetter(value = "attachment", nulls = Nulls.SKIP)
        public Builder attachment(Optional<InvoiceAttachment> attachment) {
            this.attachment = attachment;
            return this;
        }

        public Builder attachment(InvoiceAttachment attachment) {
            this.attachment = Optional.ofNullable(attachment);
            return this;
        }

        @JsonSetter(value = "errors", nulls = Nulls.SKIP)
        public Builder errors(Optional<List<Error>> errors) {
            this.errors = errors;
            return this;
        }

        public Builder errors(List<Error> errors) {
            this.errors = Optional.ofNullable(errors);
            return this;
        }

        public CreateInvoiceAttachmentResponse build() {
            return new CreateInvoiceAttachmentResponse(attachment, errors, additionalProperties);
        }
    }
}
