/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateCustomerResponse.Builder.class)
public final class CreateCustomerResponse {
    private final Optional<List<Error>> errors;

    private final Optional<Customer> customer;

    private final Map<String, Object> additionalProperties;

    private CreateCustomerResponse(
            Optional<List<Error>> errors, Optional<Customer> customer, Map<String, Object> additionalProperties) {
        this.errors = errors;
        this.customer = customer;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Any errors that occurred during the request.
     */
    @JsonProperty("errors")
    public Optional<List<Error>> getErrors() {
        return errors;
    }

    /**
     * @return The created customer.
     */
    @JsonProperty("customer")
    public Optional<Customer> getCustomer() {
        return customer;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateCustomerResponse && equalTo((CreateCustomerResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateCustomerResponse other) {
        return errors.equals(other.errors) && customer.equals(other.customer);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.errors, this.customer);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Error>> errors = Optional.empty();

        private Optional<Customer> customer = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateCustomerResponse other) {
            errors(other.getErrors());
            customer(other.getCustomer());
            return this;
        }

        @JsonSetter(value = "errors", nulls = Nulls.SKIP)
        public Builder errors(Optional<List<Error>> errors) {
            this.errors = errors;
            return this;
        }

        public Builder errors(List<Error> errors) {
            this.errors = Optional.ofNullable(errors);
            return this;
        }

        @JsonSetter(value = "customer", nulls = Nulls.SKIP)
        public Builder customer(Optional<Customer> customer) {
            this.customer = customer;
            return this;
        }

        public Builder customer(Customer customer) {
            this.customer = Optional.ofNullable(customer);
            return this;
        }

        public CreateCustomerResponse build() {
            return new CreateCustomerResponse(errors, customer, additionalProperties);
        }
    }
}
