/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeviceCodePairedEventObject.Builder.class)
public final class DeviceCodePairedEventObject {
    private final Optional<DeviceCode> deviceCode;

    private final Map<String, Object> additionalProperties;

    private DeviceCodePairedEventObject(Optional<DeviceCode> deviceCode, Map<String, Object> additionalProperties) {
        this.deviceCode = deviceCode;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The created terminal checkout
     */
    @JsonProperty("device_code")
    public Optional<DeviceCode> getDeviceCode() {
        return deviceCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeviceCodePairedEventObject && equalTo((DeviceCodePairedEventObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeviceCodePairedEventObject other) {
        return deviceCode.equals(other.deviceCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.deviceCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<DeviceCode> deviceCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DeviceCodePairedEventObject other) {
            deviceCode(other.getDeviceCode());
            return this;
        }

        @JsonSetter(value = "device_code", nulls = Nulls.SKIP)
        public Builder deviceCode(Optional<DeviceCode> deviceCode) {
            this.deviceCode = deviceCode;
            return this;
        }

        public Builder deviceCode(DeviceCode deviceCode) {
            this.deviceCode = Optional.ofNullable(deviceCode);
            return this;
        }

        public DeviceCodePairedEventObject build() {
            return new DeviceCodePairedEventObject(deviceCode, additionalProperties);
        }
    }
}
