/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetChannelsRequest.Builder.class)
public final class GetChannelsRequest {
    private final String channelId;

    private final Map<String, Object> additionalProperties;

    private GetChannelsRequest(String channelId, Map<String, Object> additionalProperties) {
        this.channelId = channelId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A channel id
     */
    @JsonProperty("channel_id")
    public String getChannelId() {
        return channelId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetChannelsRequest && equalTo((GetChannelsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetChannelsRequest other) {
        return channelId.equals(other.channelId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.channelId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ChannelIdStage builder() {
        return new Builder();
    }

    public interface ChannelIdStage {
        /**
         * <p>A channel id</p>
         */
        _FinalStage channelId(@NotNull String channelId);

        Builder from(GetChannelsRequest other);
    }

    public interface _FinalStage {
        GetChannelsRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ChannelIdStage, _FinalStage {
        private String channelId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetChannelsRequest other) {
            channelId(other.getChannelId());
            return this;
        }

        /**
         * <p>A channel id</p>
         * <p>A channel id</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("channel_id")
        public _FinalStage channelId(@NotNull String channelId) {
            this.channelId = Objects.requireNonNull(channelId, "channelId must not be null");
            return this;
        }

        @java.lang.Override
        public GetChannelsRequest build() {
            return new GetChannelsRequest(channelId, additionalProperties);
        }
    }
}
