/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListPaymentLinksResponse.Builder.class)
public final class ListPaymentLinksResponse {
    private final Optional<List<Error>> errors;

    private final Optional<List<PaymentLink>> paymentLinks;

    private final Optional<String> cursor;

    private final Map<String, Object> additionalProperties;

    private ListPaymentLinksResponse(
            Optional<List<Error>> errors,
            Optional<List<PaymentLink>> paymentLinks,
            Optional<String> cursor,
            Map<String, Object> additionalProperties) {
        this.errors = errors;
        this.paymentLinks = paymentLinks;
        this.cursor = cursor;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Errors that occurred during the request.
     */
    @JsonProperty("errors")
    public Optional<List<Error>> getErrors() {
        return errors;
    }

    /**
     * @return The list of payment links.
     */
    @JsonProperty("payment_links")
    public Optional<List<PaymentLink>> getPaymentLinks() {
        return paymentLinks;
    }

    /**
     * @return When a response is truncated, it includes a cursor that you can use in a subsequent request
     * to retrieve the next set of gift cards. If a cursor is not present, this is the final response.
     * For more information, see <a href="https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination">Pagination</a>.
     */
    @JsonProperty("cursor")
    public Optional<String> getCursor() {
        return cursor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListPaymentLinksResponse && equalTo((ListPaymentLinksResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListPaymentLinksResponse other) {
        return errors.equals(other.errors) && paymentLinks.equals(other.paymentLinks) && cursor.equals(other.cursor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.errors, this.paymentLinks, this.cursor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Error>> errors = Optional.empty();

        private Optional<List<PaymentLink>> paymentLinks = Optional.empty();

        private Optional<String> cursor = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListPaymentLinksResponse other) {
            errors(other.getErrors());
            paymentLinks(other.getPaymentLinks());
            cursor(other.getCursor());
            return this;
        }

        @JsonSetter(value = "errors", nulls = Nulls.SKIP)
        public Builder errors(Optional<List<Error>> errors) {
            this.errors = errors;
            return this;
        }

        public Builder errors(List<Error> errors) {
            this.errors = Optional.ofNullable(errors);
            return this;
        }

        @JsonSetter(value = "payment_links", nulls = Nulls.SKIP)
        public Builder paymentLinks(Optional<List<PaymentLink>> paymentLinks) {
            this.paymentLinks = paymentLinks;
            return this;
        }

        public Builder paymentLinks(List<PaymentLink> paymentLinks) {
            this.paymentLinks = Optional.ofNullable(paymentLinks);
            return this;
        }

        @JsonSetter(value = "cursor", nulls = Nulls.SKIP)
        public Builder cursor(Optional<String> cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder cursor(String cursor) {
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        public ListPaymentLinksResponse build() {
            return new ListPaymentLinksResponse(errors, paymentLinks, cursor, additionalProperties);
        }
    }
}
