/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LoyaltyEventAccumulatePromotionPoints.Builder.class)
public final class LoyaltyEventAccumulatePromotionPoints {
    private final Optional<String> loyaltyProgramId;

    private final Optional<String> loyaltyPromotionId;

    private final int points;

    private final String orderId;

    private final Map<String, Object> additionalProperties;

    private LoyaltyEventAccumulatePromotionPoints(
            Optional<String> loyaltyProgramId,
            Optional<String> loyaltyPromotionId,
            int points,
            String orderId,
            Map<String, Object> additionalProperties) {
        this.loyaltyProgramId = loyaltyProgramId;
        this.loyaltyPromotionId = loyaltyPromotionId;
        this.points = points;
        this.orderId = orderId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The Square-assigned ID of the <a href="entity:LoyaltyProgram">loyalty program</a>.
     */
    @JsonProperty("loyalty_program_id")
    public Optional<String> getLoyaltyProgramId() {
        return loyaltyProgramId;
    }

    /**
     * @return The Square-assigned ID of the <a href="entity:LoyaltyPromotion">loyalty promotion</a>.
     */
    @JsonProperty("loyalty_promotion_id")
    public Optional<String> getLoyaltyPromotionId() {
        return loyaltyPromotionId;
    }

    /**
     * @return The number of points earned by the event.
     */
    @JsonProperty("points")
    public int getPoints() {
        return points;
    }

    /**
     * @return The ID of the <a href="entity:Order">order</a> for which the buyer earned the promotion points.
     * Only applications that use the Orders API to process orders can trigger this event.
     */
    @JsonProperty("order_id")
    public String getOrderId() {
        return orderId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LoyaltyEventAccumulatePromotionPoints
                && equalTo((LoyaltyEventAccumulatePromotionPoints) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LoyaltyEventAccumulatePromotionPoints other) {
        return loyaltyProgramId.equals(other.loyaltyProgramId)
                && loyaltyPromotionId.equals(other.loyaltyPromotionId)
                && points == other.points
                && orderId.equals(other.orderId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.loyaltyProgramId, this.loyaltyPromotionId, this.points, this.orderId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PointsStage builder() {
        return new Builder();
    }

    public interface PointsStage {
        OrderIdStage points(int points);

        Builder from(LoyaltyEventAccumulatePromotionPoints other);
    }

    public interface OrderIdStage {
        _FinalStage orderId(@NotNull String orderId);
    }

    public interface _FinalStage {
        LoyaltyEventAccumulatePromotionPoints build();

        _FinalStage loyaltyProgramId(Optional<String> loyaltyProgramId);

        _FinalStage loyaltyProgramId(String loyaltyProgramId);

        _FinalStage loyaltyPromotionId(Optional<String> loyaltyPromotionId);

        _FinalStage loyaltyPromotionId(String loyaltyPromotionId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PointsStage, OrderIdStage, _FinalStage {
        private int points;

        private String orderId;

        private Optional<String> loyaltyPromotionId = Optional.empty();

        private Optional<String> loyaltyProgramId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(LoyaltyEventAccumulatePromotionPoints other) {
            loyaltyProgramId(other.getLoyaltyProgramId());
            loyaltyPromotionId(other.getLoyaltyPromotionId());
            points(other.getPoints());
            orderId(other.getOrderId());
            return this;
        }

        /**
         * <p>The number of points earned by the event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("points")
        public OrderIdStage points(int points) {
            this.points = points;
            return this;
        }

        /**
         * <p>The ID of the <a href="entity:Order">order</a> for which the buyer earned the promotion points.
         * Only applications that use the Orders API to process orders can trigger this event.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("order_id")
        public _FinalStage orderId(@NotNull String orderId) {
            this.orderId = Objects.requireNonNull(orderId, "orderId must not be null");
            return this;
        }

        /**
         * <p>The Square-assigned ID of the <a href="entity:LoyaltyPromotion">loyalty promotion</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage loyaltyPromotionId(String loyaltyPromotionId) {
            this.loyaltyPromotionId = Optional.ofNullable(loyaltyPromotionId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "loyalty_promotion_id", nulls = Nulls.SKIP)
        public _FinalStage loyaltyPromotionId(Optional<String> loyaltyPromotionId) {
            this.loyaltyPromotionId = loyaltyPromotionId;
            return this;
        }

        /**
         * <p>The Square-assigned ID of the <a href="entity:LoyaltyProgram">loyalty program</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage loyaltyProgramId(String loyaltyProgramId) {
            this.loyaltyProgramId = Optional.ofNullable(loyaltyProgramId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "loyalty_program_id", nulls = Nulls.SKIP)
        public _FinalStage loyaltyProgramId(Optional<String> loyaltyProgramId) {
            this.loyaltyProgramId = loyaltyProgramId;
            return this;
        }

        @java.lang.Override
        public LoyaltyEventAccumulatePromotionPoints build() {
            return new LoyaltyEventAccumulatePromotionPoints(
                    loyaltyProgramId, loyaltyPromotionId, points, orderId, additionalProperties);
        }
    }
}
