/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LoyaltyProgramRewardDefinitionScope {
    public static final LoyaltyProgramRewardDefinitionScope CATEGORY =
            new LoyaltyProgramRewardDefinitionScope(Value.CATEGORY, "CATEGORY");

    public static final LoyaltyProgramRewardDefinitionScope ORDER =
            new LoyaltyProgramRewardDefinitionScope(Value.ORDER, "ORDER");

    public static final LoyaltyProgramRewardDefinitionScope ITEM_VARIATION =
            new LoyaltyProgramRewardDefinitionScope(Value.ITEM_VARIATION, "ITEM_VARIATION");

    private final Value value;

    private final String string;

    LoyaltyProgramRewardDefinitionScope(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LoyaltyProgramRewardDefinitionScope
                        && this.string.equals(((LoyaltyProgramRewardDefinitionScope) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CATEGORY:
                return visitor.visitCategory();
            case ORDER:
                return visitor.visitOrder();
            case ITEM_VARIATION:
                return visitor.visitItemVariation();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LoyaltyProgramRewardDefinitionScope valueOf(String value) {
        switch (value) {
            case "CATEGORY":
                return CATEGORY;
            case "ORDER":
                return ORDER;
            case "ITEM_VARIATION":
                return ITEM_VARIATION;
            default:
                return new LoyaltyProgramRewardDefinitionScope(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ORDER,

        ITEM_VARIATION,

        CATEGORY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOrder();

        T visitItemVariation();

        T visitCategory();

        T visitUnknown(String unknownType);
    }
}
