/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SearchSubscriptionsQuery.Builder.class)
public final class SearchSubscriptionsQuery {
    private final Optional<SearchSubscriptionsFilter> filter;

    private final Map<String, Object> additionalProperties;

    private SearchSubscriptionsQuery(
            Optional<SearchSubscriptionsFilter> filter, Map<String, Object> additionalProperties) {
        this.filter = filter;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A list of query expressions.
     */
    @JsonProperty("filter")
    public Optional<SearchSubscriptionsFilter> getFilter() {
        return filter;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SearchSubscriptionsQuery && equalTo((SearchSubscriptionsQuery) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SearchSubscriptionsQuery other) {
        return filter.equals(other.filter);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.filter);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<SearchSubscriptionsFilter> filter = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SearchSubscriptionsQuery other) {
            filter(other.getFilter());
            return this;
        }

        @JsonSetter(value = "filter", nulls = Nulls.SKIP)
        public Builder filter(Optional<SearchSubscriptionsFilter> filter) {
            this.filter = filter;
            return this;
        }

        public Builder filter(SearchSubscriptionsFilter filter) {
            this.filter = Optional.ofNullable(filter);
            return this;
        }

        public SearchSubscriptionsQuery build() {
            return new SearchSubscriptionsQuery(filter, additionalProperties);
        }
    }
}
