/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TransferOrderUpdatedEventObject.Builder.class)
public final class TransferOrderUpdatedEventObject {
    private final Optional<TransferOrder> transferOrder;

    private final Map<String, Object> additionalProperties;

    private TransferOrderUpdatedEventObject(
            Optional<TransferOrder> transferOrder, Map<String, Object> additionalProperties) {
        this.transferOrder = transferOrder;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The updated transfer_order.
     */
    @JsonProperty("transfer_order")
    public Optional<TransferOrder> getTransferOrder() {
        return transferOrder;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TransferOrderUpdatedEventObject && equalTo((TransferOrderUpdatedEventObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TransferOrderUpdatedEventObject other) {
        return transferOrder.equals(other.transferOrder);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.transferOrder);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<TransferOrder> transferOrder = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TransferOrderUpdatedEventObject other) {
            transferOrder(other.getTransferOrder());
            return this;
        }

        /**
         * <p>The updated transfer_order.</p>
         */
        @JsonSetter(value = "transfer_order", nulls = Nulls.SKIP)
        public Builder transferOrder(Optional<TransferOrder> transferOrder) {
            this.transferOrder = transferOrder;
            return this;
        }

        public Builder transferOrder(TransferOrder transferOrder) {
            this.transferOrder = Optional.ofNullable(transferOrder);
            return this;
        }

        public TransferOrderUpdatedEventObject build() {
            return new TransferOrderUpdatedEventObject(transferOrder, additionalProperties);
        }
    }
}
