/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.Nullable;
import com.squareup.square.core.NullableNonemptyFilter;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TransferOrderGoodsReceiptLineItem.Builder.class)
public final class TransferOrderGoodsReceiptLineItem {
    private final String transferOrderLineUid;

    private final Optional<String> quantityReceived;

    private final Optional<String> quantityDamaged;

    private final Optional<String> quantityCanceled;

    private final Map<String, Object> additionalProperties;

    private TransferOrderGoodsReceiptLineItem(
            String transferOrderLineUid,
            Optional<String> quantityReceived,
            Optional<String> quantityDamaged,
            Optional<String> quantityCanceled,
            Map<String, Object> additionalProperties) {
        this.transferOrderLineUid = transferOrderLineUid;
        this.quantityReceived = quantityReceived;
        this.quantityDamaged = quantityDamaged;
        this.quantityCanceled = quantityCanceled;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique identifier of the Transfer Order line being received
     */
    @JsonProperty("transfer_order_line_uid")
    public String getTransferOrderLineUid() {
        return transferOrderLineUid;
    }

    /**
     * @return The quantity received for this line item as a decimal string (e.g. &quot;10.5&quot;).
     * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of IN_STOCK.
     */
    @JsonIgnore
    public Optional<String> getQuantityReceived() {
        if (quantityReceived == null) {
            return Optional.empty();
        }
        return quantityReceived;
    }

    /**
     * @return The quantity that was damaged during shipping/handling as a decimal string (e.g. &quot;1.5&quot;).
     * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of WASTE.
     */
    @JsonIgnore
    public Optional<String> getQuantityDamaged() {
        if (quantityDamaged == null) {
            return Optional.empty();
        }
        return quantityDamaged;
    }

    /**
     * @return The quantity that was canceled during shipping/handling as a decimal string (e.g. &quot;1.5&quot;). These will be immediately added to inventory in the source location.
     */
    @JsonIgnore
    public Optional<String> getQuantityCanceled() {
        if (quantityCanceled == null) {
            return Optional.empty();
        }
        return quantityCanceled;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("quantity_received")
    private Optional<String> _getQuantityReceived() {
        return quantityReceived;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("quantity_damaged")
    private Optional<String> _getQuantityDamaged() {
        return quantityDamaged;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("quantity_canceled")
    private Optional<String> _getQuantityCanceled() {
        return quantityCanceled;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TransferOrderGoodsReceiptLineItem && equalTo((TransferOrderGoodsReceiptLineItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TransferOrderGoodsReceiptLineItem other) {
        return transferOrderLineUid.equals(other.transferOrderLineUid)
                && quantityReceived.equals(other.quantityReceived)
                && quantityDamaged.equals(other.quantityDamaged)
                && quantityCanceled.equals(other.quantityCanceled);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.transferOrderLineUid, this.quantityReceived, this.quantityDamaged, this.quantityCanceled);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TransferOrderLineUidStage builder() {
        return new Builder();
    }

    public interface TransferOrderLineUidStage {
        /**
         * <p>The unique identifier of the Transfer Order line being received</p>
         */
        _FinalStage transferOrderLineUid(@NotNull String transferOrderLineUid);

        Builder from(TransferOrderGoodsReceiptLineItem other);
    }

    public interface _FinalStage {
        TransferOrderGoodsReceiptLineItem build();

        /**
         * <p>The quantity received for this line item as a decimal string (e.g. &quot;10.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of IN_STOCK.</p>
         */
        _FinalStage quantityReceived(Optional<String> quantityReceived);

        _FinalStage quantityReceived(String quantityReceived);

        _FinalStage quantityReceived(Nullable<String> quantityReceived);

        /**
         * <p>The quantity that was damaged during shipping/handling as a decimal string (e.g. &quot;1.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of WASTE.</p>
         */
        _FinalStage quantityDamaged(Optional<String> quantityDamaged);

        _FinalStage quantityDamaged(String quantityDamaged);

        _FinalStage quantityDamaged(Nullable<String> quantityDamaged);

        /**
         * <p>The quantity that was canceled during shipping/handling as a decimal string (e.g. &quot;1.5&quot;). These will be immediately added to inventory in the source location.</p>
         */
        _FinalStage quantityCanceled(Optional<String> quantityCanceled);

        _FinalStage quantityCanceled(String quantityCanceled);

        _FinalStage quantityCanceled(Nullable<String> quantityCanceled);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TransferOrderLineUidStage, _FinalStage {
        private String transferOrderLineUid;

        private Optional<String> quantityCanceled = Optional.empty();

        private Optional<String> quantityDamaged = Optional.empty();

        private Optional<String> quantityReceived = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TransferOrderGoodsReceiptLineItem other) {
            transferOrderLineUid(other.getTransferOrderLineUid());
            quantityReceived(other.getQuantityReceived());
            quantityDamaged(other.getQuantityDamaged());
            quantityCanceled(other.getQuantityCanceled());
            return this;
        }

        /**
         * <p>The unique identifier of the Transfer Order line being received</p>
         * <p>The unique identifier of the Transfer Order line being received</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("transfer_order_line_uid")
        public _FinalStage transferOrderLineUid(@NotNull String transferOrderLineUid) {
            this.transferOrderLineUid =
                    Objects.requireNonNull(transferOrderLineUid, "transferOrderLineUid must not be null");
            return this;
        }

        /**
         * <p>The quantity that was canceled during shipping/handling as a decimal string (e.g. &quot;1.5&quot;). These will be immediately added to inventory in the source location.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage quantityCanceled(Nullable<String> quantityCanceled) {
            if (quantityCanceled.isNull()) {
                this.quantityCanceled = null;
            } else if (quantityCanceled.isEmpty()) {
                this.quantityCanceled = Optional.empty();
            } else {
                this.quantityCanceled = Optional.of(quantityCanceled.get());
            }
            return this;
        }

        /**
         * <p>The quantity that was canceled during shipping/handling as a decimal string (e.g. &quot;1.5&quot;). These will be immediately added to inventory in the source location.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage quantityCanceled(String quantityCanceled) {
            this.quantityCanceled = Optional.ofNullable(quantityCanceled);
            return this;
        }

        /**
         * <p>The quantity that was canceled during shipping/handling as a decimal string (e.g. &quot;1.5&quot;). These will be immediately added to inventory in the source location.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "quantity_canceled", nulls = Nulls.SKIP)
        public _FinalStage quantityCanceled(Optional<String> quantityCanceled) {
            this.quantityCanceled = quantityCanceled;
            return this;
        }

        /**
         * <p>The quantity that was damaged during shipping/handling as a decimal string (e.g. &quot;1.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of WASTE.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage quantityDamaged(Nullable<String> quantityDamaged) {
            if (quantityDamaged.isNull()) {
                this.quantityDamaged = null;
            } else if (quantityDamaged.isEmpty()) {
                this.quantityDamaged = Optional.empty();
            } else {
                this.quantityDamaged = Optional.of(quantityDamaged.get());
            }
            return this;
        }

        /**
         * <p>The quantity that was damaged during shipping/handling as a decimal string (e.g. &quot;1.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of WASTE.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage quantityDamaged(String quantityDamaged) {
            this.quantityDamaged = Optional.ofNullable(quantityDamaged);
            return this;
        }

        /**
         * <p>The quantity that was damaged during shipping/handling as a decimal string (e.g. &quot;1.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of WASTE.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "quantity_damaged", nulls = Nulls.SKIP)
        public _FinalStage quantityDamaged(Optional<String> quantityDamaged) {
            this.quantityDamaged = quantityDamaged;
            return this;
        }

        /**
         * <p>The quantity received for this line item as a decimal string (e.g. &quot;10.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of IN_STOCK.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage quantityReceived(Nullable<String> quantityReceived) {
            if (quantityReceived.isNull()) {
                this.quantityReceived = null;
            } else if (quantityReceived.isEmpty()) {
                this.quantityReceived = Optional.empty();
            } else {
                this.quantityReceived = Optional.of(quantityReceived.get());
            }
            return this;
        }

        /**
         * <p>The quantity received for this line item as a decimal string (e.g. &quot;10.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of IN_STOCK.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage quantityReceived(String quantityReceived) {
            this.quantityReceived = Optional.ofNullable(quantityReceived);
            return this;
        }

        /**
         * <p>The quantity received for this line item as a decimal string (e.g. &quot;10.5&quot;).
         * These items will be added to the destination <a href="entity:Location">Location</a>'s inventory with <a href="entity:InventoryState">InventoryState</a> of IN_STOCK.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "quantity_received", nulls = Nulls.SKIP)
        public _FinalStage quantityReceived(Optional<String> quantityReceived) {
            this.quantityReceived = quantityReceived;
            return this;
        }

        @java.lang.Override
        public TransferOrderGoodsReceiptLineItem build() {
            return new TransferOrderGoodsReceiptLineItem(
                    transferOrderLineUid, quantityReceived, quantityDamaged, quantityCanceled, additionalProperties);
        }
    }
}
