/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.squareup.square.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.squareup.square.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateMerchantSettingsResponse.Builder.class)
public final class UpdateMerchantSettingsResponse {
    private final Optional<List<Error>> errors;

    private final Optional<CheckoutMerchantSettings> merchantSettings;

    private final Map<String, Object> additionalProperties;

    private UpdateMerchantSettingsResponse(
            Optional<List<Error>> errors,
            Optional<CheckoutMerchantSettings> merchantSettings,
            Map<String, Object> additionalProperties) {
        this.errors = errors;
        this.merchantSettings = merchantSettings;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Any errors that occurred when updating the merchant settings.
     */
    @JsonProperty("errors")
    public Optional<List<Error>> getErrors() {
        return errors;
    }

    /**
     * @return The updated merchant settings.
     */
    @JsonProperty("merchant_settings")
    public Optional<CheckoutMerchantSettings> getMerchantSettings() {
        return merchantSettings;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateMerchantSettingsResponse && equalTo((UpdateMerchantSettingsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateMerchantSettingsResponse other) {
        return errors.equals(other.errors) && merchantSettings.equals(other.merchantSettings);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.errors, this.merchantSettings);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Error>> errors = Optional.empty();

        private Optional<CheckoutMerchantSettings> merchantSettings = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateMerchantSettingsResponse other) {
            errors(other.getErrors());
            merchantSettings(other.getMerchantSettings());
            return this;
        }

        @JsonSetter(value = "errors", nulls = Nulls.SKIP)
        public Builder errors(Optional<List<Error>> errors) {
            this.errors = errors;
            return this;
        }

        public Builder errors(List<Error> errors) {
            this.errors = Optional.ofNullable(errors);
            return this;
        }

        @JsonSetter(value = "merchant_settings", nulls = Nulls.SKIP)
        public Builder merchantSettings(Optional<CheckoutMerchantSettings> merchantSettings) {
            this.merchantSettings = merchantSettings;
            return this;
        }

        public Builder merchantSettings(CheckoutMerchantSettings merchantSettings) {
            this.merchantSettings = Optional.ofNullable(merchantSettings);
            return this;
        }

        public UpdateMerchantSettingsResponse build() {
            return new UpdateMerchantSettingsResponse(errors, merchantSettings, additionalProperties);
        }
    }
}
